### ISSUE TITLE
[Rosie] Change the responsibility of writing the xz files, from Core to the Adapter

### ISSUE THREAD

**Issue by ricardochaves** [okfn-brasil/serenata-de-amor#384]
**What is the problem?**
Today the Rosie Core receives an `Adapter` that must have the `dataset` and a `path`.
The path is used to write the `xz` file to disk. In this scenario, the `Adapter` is responsible for collecting data from a file that it receives in the constructor, but has no responsibility to deliver the data to its destination. This makes it difficult to create an `Adapter` to write data to the Jarbas database, for example. Maybe even an adapter for sending information to another API.

**How can this be addressed?**
Core expects to receive an `Adapter` with the `dataset` and a `save()` method that will execute in the place where it currently writes the file with `to_csv`. With this we can create an Adapter to write read the file to disk, but save the data in the Jarbas database without having to change the Core.

**Who could help with this issue?**
I can do the task myself if you find the solution interesting. I want to make the whole change to Rosei use the Jarbas database, but as I have little time the ideal would be small changes in the design to be preparing the way to just plug in new codes.
Another reason for small tasks is that anyone can continue with the task if it takes too long.
If you think it's impractical or not the way I close the Issues

**Comment by cuducos** [comment]
Hi @ricardochaves,

Many thanks for your interest. Before diving in, I'd like to poorly draft read/write responsibilities here:

1. `serenata-toolbox` is in charge of reading _original data_ from the source
    1. Today it writes it to a compressed CSV with the `.xz` extension
    1. In the future this is not necessary, we could pass a database `postgres://user:pass@host/name` instead of a `path` and save data into the database
2. Rosie needs an adapter to find _original data_
    1. As of today, data is a`.xz` and so the `Adapter` takes the path to it as well as relevant information about the datatset (main columns)
    1. In the future, if data is in a database, it could be also just a database such as `postgres://user:pass@host/name` 
3. Rosie runs and now she has generated new data (a.k.a. suspicions)
    1. Today she generates another `.xz`
    1. In the future, if data is in a database, she can simply update the same database

Sorry about this long introduction, but I thought it was necessary to clarify which step of read & write we were talking about. If I got your proposal right, the idea is to change the `save()` method of the `Adapter` to make the switch described in step 3, isn't it? If so I do agree that a `save()` method writing to the database would be a nice improvement.

However I'm just worried that this is not the step we need right now. We cannot think of updating the database if we are not sure this database is updated. What I mean is that maybe what we need to be done _first_ is step 1 (write updated data about reimbursements to the database) to, then, go to _step 3_ (update reimbursements with suspicions in the database). Otherwise Rosie might end up trying to update a non-existent reimbursement (sure a simple `if` might fix that, but we would be unable to actually update original data in this database).

Does that make sense to you?

**Comment by ricardochaves** [comment]
Makes sense! I'll close and start looking at the database.
