### ISSUE TITLE
Create priority field to choose which anomaly will be posted on twitter

### ISSUE THREAD

**Issue by ArthurSens** [okfn-brasil/serenata-de-amor#478]
Today, Jarbas has a limitation of tweets he can make per day, but Rosie finds more anomalies than this limit.

The anomalies are chosen randomly and then published on twitter.

We want that the anomalies can be sorted by some type of priority and when publishing on twitter, choose the anomaly with higher priority.

In an initial stage we can calculate the average and standard deviation of expenses by category, and the anomalies would be prioritized by how far it is from the mean + standard deviation of the category.

If we dig deeper, we could use more and more attributes to decide this priority field.

**Comment by cuducos** [comment]
> Today, Jarbas has a limitation of tweets he can make per day, but Rosie finds more anomalies than this limit.

I wouldn't say it's a limtation. If is there a pending tweet, it's just a matter of running `python manage.py tweet` or, to automate it, change the [`cronjob` config](https://github.com/okfn-brasil/serenata-de-amor/blob/master/contrib/crontab/crontab).

> The anomalies are chosen randomly and then published on twitter.

Actually, they are not that random. It tweets only tweets [from the top quartile](https://github.com/okfn-brasil/serenata-de-amor/blob/master/jarbas/chamber_of_deputies/twitter.py#L57-L58) based on [how recent the suspicion is](https://github.com/okfn-brasil/serenata-de-amor/blob/master/jarbas/chamber_of_deputies/twitter.py#L51). This is actually strategic, because because it is easier to pressure congress people that are still in office.

> We want that the anomalies can be sorted by some type of priority and when publishing on twitter, choose the anomaly with higher priority.

This is indeed interesting, since we still keep in might that recent issue date is still important from the civic engagement point of view.

> In an initial stage we can calculate the average and standard deviation of expenses by category, and the anomalies would be prioritized by how far it is from the mean + standard deviation of the category.

Maybe this [old and unaddressed issue](https://github.com/okfn-brasil/rosie/issues/61) might be useful:

> Today we have no way to track the amount of each suspicion that might be returned to the treasure in case the suspicion is confirmed and took forward. I believe that even if each classifier has it's own logic, it's possible to add a field with that data:
>
> * irregular CNPJ/CPF or electoral expense: 100%
> * subquotas: the difference between the total spent and the subquota monthly limit
> * meal outlier: probably a value between the total_net_vale and mean + std
> * and so on…

**Comment by ArthurSens** [comment]
> I wouldn't say it's a limtation. If is there a pending tweet, it's just a matter of running python manage.py tweet or, to automate it, change the cronjob config.

You're saying that every recent(from 2 years ago until now) anomaly found by rosie will be tweeted? I find that quite strange, since I see only 1 or 2 tweets per day.

> This is indeed interesting, since we still keep in might that recent issue date is still important from the civic engagement point of view.

Yeah sure, I agree that the more recent the anomaly is, the higher priority it should have to be tweeted

> Maybe this old and unaddressed issue might be useful:

Thank you for this, that's some really good ideas to prioritize tweets.
 I think it's even relevant information to add to jarbas front-end!!

I will try to find some time and start developing these new classifiers

**Comment by cuducos** [comment]
> You're saying that every recent(from 2 years ago until now) anomaly found by rosie will be tweeted? I find that quite strange, since I see only 1 or 2 tweets per day.

No. I'm not making promises about the future. I'm only saying that changing the pace of tweets is extremely easy and we actually change it every now and then to adjust the pace to the queue ; )

**Comment by ArthurSens** [comment]
Oh I see

Thanks for the clarification
